server {
    listen       443 ssl;
    server_name advertiser-travel.local;

    ssl_certificate /etc/ssl/fledge/advertiser-travel.local.pem;
    ssl_certificate_key /etc/ssl/fledge/advertiser-travel.local-key.pem;

    access_log           /var/log/nginx/advertiser-travel.access.log;
    error_log            /var/log/nginx/advertiser-travel.error.log;

    add_header X-Allow-FLEDGE true;
    add_header Supports-Loading-Mode fenced-frame;

    root /usr/share/nginx/html/advertiser-travel.local;
    index  index.html;
}
