server {
    listen       443 ssl;
    server_name publisher-news.local;

    ssl_certificate /etc/ssl/fledge/publisher-news.local.pem;
    ssl_certificate_key /etc/ssl/fledge/publisher-news.local-key.pem;

    access_log           /var/log/nginx/publisher-news.access.log;
    error_log            /var/log/nginx/publisher-news.error.log;

    add_header X-Allow-FLEDGE true;
    add_header Supports-Loading-Mode fenced-frame;

    root /usr/share/nginx/html/publisher-news.local;
    index  index.html;
}
