server {
    listen       443 ssl;
    server_name ssp1.local;

    ssl_certificate /etc/ssl/fledge/ssp1.local.pem;
    ssl_certificate_key /etc/ssl/fledge/ssp1.local-key.pem;

    access_log           /var/log/nginx/ssp1.access.log;
    error_log            /var/log/nginx/ssp1.error.log;

    add_header X-Allow-FLEDGE true;
    add_header Supports-Loading-Mode fenced-frame;

    root /usr/share/nginx/html/ssp1.local;
}
